---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-helm-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marcocaberletti/argocd-poc.git
    targetRevision: main
    path: apps/argocd/helm-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
